### ISSUE TITLE
Implement a way to export the FactorGraph data structure to a format like graphviz

### ISSUE THREAD

**Issue by JnsJensen** [AU-Master-Thesis/gbp-rs#3]
I know that there are some packages for this on crates.io

Use a similar format for the nodes as https://gaussianbp.github.io/
where the factors are squares and the variables are circles.

**Comment by kpbaks** [comment]
Use different colors for the different factor types:

- Pose Factor
- Dynamics Factor
- Obstacle Factor

**Comment by kpbaks** [comment]
Use fig. 2 from the paper as inspiration.
